config/routes.rb
Rails.application.routes.draw do
  resources :bugs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bug.rb
class Bug < ApplicationRecord
    validates :description, :priority, :assignee, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
   before_action :set_bug, only:%i[ update destroy]

 def index
    @bugs = Bug.all
    respond_to do |format|
      format.html
      format.turbo_stream
 end
end

 def create 
    @bug = Bug.create(bug_params)
    respond_to do |format|
      if @bug.save
        format.turbo_stream
        format.html { redirect_to bugs_path, notice: 'Bug was successfully created.' }
    else 
         format.turbo_stream { render :new, status: :unprocessable_entity }
         format.html { render :new, status: :unprocessable_entity }
      end 
     end
   end
         
      

 def update 
   respond_to do |format|
   if @bug.update(bug_params)
    format.turbo_stream
    format.html { redirect_to bugs_path, notice: 'Bug was successfully updated' }
   else 
    format.turbo_stream { render :edit, status: :unprocessable_entity }
    format.html { render :edit, status: :unprocessable_entity }   
    end
   end
 end

 def destroy 
   @bug.destroy
   respond_to do |format|
      format.turbo_stream
      format.html { redirect_to bugs_path, notice: 'Bug was successfully deleted'}
    end
 end 

 private
  def set_bug
    @bug = Bug.find(params[:id])
  end

  def bug_params
     params.require(:bug).permit(:description, :priority, :assignee)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_bug.html.erb
<div id="<%= dom_id(bug) %>">
  <p><strong>Description:</strong> <%= bug.description %></p>
  <p><strong>Priority:</strong> <%= bug.priority %></p>
  <p><strong>Assignee:</strong> <%= bug.assignee %></p>

  <%= link_to 'Edit', edit_bug_path(bug), class: 'btn btn-primary' %>
  <%= link_to 'Delete', bug, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
</div>

app/views/bugs/_bugs_list.html.erb
<div id="bugs">
  <% @bugs.each do |bug| %>
    <%= render 'bugs/bug', bug: bug %>
  <% end %>
</div>

<div>
</div>

app/views/bugs/create.html.erb
<%= turbo_stream.append 'bugs', partial: 'bugs/bug', locals: { bug: @bug} %>

app/views/bugs/create.turbo_stream.erb
<%= turbo_stream.append 'bugs', partial: 'bugs/bug', locals: { bug: @bug} %>

app/views/bugs/destroy.html.erb
<%= turbo_stream.remove @bug %>

app/views/bugs/destroy.turbo_stream.erb
<%= turbo_stream.remove @bug %>

app/views/bugs/index.html.erb
<%= turbo_stream.update 'bugs', partial: 'bugs/bugs_list', locals: { bugs: @bugs } %>

app/views/bugs/show.html.erb
<h1>Bug Details</h1>
<turbo-frame id="bug-details" src="<%= bug_path(@bug) %>">
<%= render 'bugs/bug', bug: @bug %>
</turbo-frame>

app/views/bugs/update.html.erb
<%= turbo_stream.replace @bug, partial: 'bugs/bug', locals: { bug: @bug } %>

app/views/bugs/update.turbo_stream.erb
<%= turbo_stream.replace @bug, partial: 'bugs/bug', locals: { bug: @bug } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugTrackerBackend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_pack_tag 'tailwind' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>